<?php

namespace Database\Seeders;

use App\Library\Database\AutoIncrement;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QualificationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $qualifications = [
            ['qualification_id' => 1, 'qualification_name' => 'Xth Class'],
            ['qualification_id' => 2, 'qualification_name' => 'XIIth Class'],
            ['qualification_id' => 3, 'qualification_name' => 'B.A. Bachelor of Arts'],
            ['qualification_id' => 4, 'qualification_name' => 'B.Arch. Bachelor of Architecture'],
            ['qualification_id' => 5, 'qualification_name' => 'B.Com. Bachelor of Commerce'],
            ['qualification_id' => 6, 'qualification_name' => 'BCA Bachelor of Computer Applications'],
            ['qualification_id' => 7, 'qualification_name' => 'BBA Bachelor of Business Administration'],
            ['qualification_id' => 8, 'qualification_name' => 'B.A.M.S. Bachelor of Ayurvedic Medicine & Surgery'],
            ['qualification_id' => 9, 'qualification_name' => 'B.Sc. (Computer Science) Bachelor of Computer Science'],
            ['qualification_id' => 10, 'qualification_name' => 'BDS Bachelor of Dental Surgery'],
            ['qualification_id' => 11, 'qualification_name' => 'B.Des. - B.D. Bachelor of Design'],
            ['qualification_id' => 12, 'qualification_name' => 'B.E./B.Tech. Bachelor of Engineering - Bachelor of Technology'],
            ['qualification_id' => 13, 'qualification_name' => 'BFA - BVA Bachelor of Fine Arts'],
            ['qualification_id' => 14, 'qualification_name' => 'B.F.Sc. - B.Sc. (Fisheries) Bachelor of Fisheries Science'],
            ['qualification_id' => 15, 'qualification_name' => 'B.A. - B.Sc. (Home Science) Bachelor of Home Science'],
            ['qualification_id' => 16, 'qualification_name' => 'B.H.M.S. Bachelor of Homeopathic Medicine and Surgery'],
            ['qualification_id' => 17, 'qualification_name' => 'L.L.B. Bachelor of Laws'],
            ['qualification_id' => 18, 'qualification_name' => 'B.Lib. - B.Lib.Sc. Bachelor of Library Science'],
            ['qualification_id' => 19, 'qualification_name' => 'B.M.C. - B.M.M. Bachelor of Mass Communications'],
            ['qualification_id' => 20, 'qualification_name' => 'B.Sc. (Nursing) Bachelor of Nursing'],
            ['qualification_id' => 21, 'qualification_name' => 'B.Pharm. Bachelor of Pharmacy'],
            ['qualification_id' => 22, 'qualification_name' => 'B.P.Ed. Bachelor of Physical Education'],
            ['qualification_id' => 23, 'qualification_name' => 'B.P.T. Bachelor of Physiotherapy'],
            ['qualification_id' => 24, 'qualification_name' => 'B.Sc. Bachelor of Science'],
            ['qualification_id' => 25, 'qualification_name' => 'BSW or B.A. (SW) Bachelor of Social Work'],
            ['qualification_id' => 26, 'qualification_name' => 'B.V.Sc. Bachelor of Veterinary Science & Animal Husbandry'],
            ['qualification_id' => 27, 'qualification_name' => 'B.Sc. (Agriculture) Bachelor of Agriculture'],
            ['qualification_id' => 28, 'qualification_name' => 'B.A. (Hons) Applied Psychology'],
            ['qualification_id' => 29, 'qualification_name' => 'B.A. (Hons) Bengali'],
            ['qualification_id' => 30, 'qualification_name' => 'B.A. (Hons) Economics'],
            ['qualification_id' => 31, 'qualification_name' => 'B.A. (Hons) French'],
            ['qualification_id' => 32, 'qualification_name' => 'B.A. (Hons) German'],
            ['qualification_id' => 33, 'qualification_name' => 'B.A. (Hons) History'],
            ['qualification_id' => 34, 'qualification_name' => 'B.A. (Hons) Italian'],
            ['qualification_id' => 35, 'qualification_name' => 'B.A. (Hons) Music'],
            ['qualification_id' => 36, 'qualification_name' => 'B.A. (Hons) Philosophy'],
            ['qualification_id' => 37, 'qualification_name' => 'B.A. (Hons) Psychology'],
            ['qualification_id' => 38, 'qualification_name' => 'B.A. (Hons) Sanskrit'],
            ['qualification_id' => 39, 'qualification_name' => 'B.A. (Hons) Sociology'],
            ['qualification_id' => 40, 'qualification_name' => 'B.A. (Hons) Urdu'],
            ['qualification_id' => 41, 'qualification_name' => 'B.A. Functional Hindi'],
            ['qualification_id' => 42, 'qualification_name' => 'B.A. (Hons) Arabic'],
            ['qualification_id' => 43, 'qualification_name' => 'B.A. (Hons) Business Economics (BBE)'],
            ['qualification_id' => 44, 'qualification_name' => 'B.A. (Hons) English'],
            ['qualification_id' => 45, 'qualification_name' => 'B.A. (Hons) Geography'],
            ['qualification_id' => 46, 'qualification_name' => 'B.A. (Hons) Hindi'],
            ['qualification_id' => 47, 'qualification_name' => 'B.A. (Hons) Patrakarita Evam Jansanchar'],
            ['qualification_id' => 48, 'qualification_name' => 'B.A. (Hons) Journalism'],
            ['qualification_id' => 49, 'qualification_name' => 'B.A. (Hons) Persian'],
            ['qualification_id' => 50, 'qualification_name' => 'B.A. (Hons) Political Science'],
            ['qualification_id' => 51, 'qualification_name' => 'B.A. (Hons) Punjabi'],
            ['qualification_id' => 52, 'qualification_name' => 'B.A. (Hons) Social Work'],
            ['qualification_id' => 53, 'qualification_name' => 'B.A. (Hons) Spanish'],
            ['qualification_id' => 54, 'qualification_name' => 'B.A. (Hons.) Hindi Journalism and Mass Communication'],
            ['qualification_id' => 55, 'qualification_name' => 'B.A. Vocational Studies'],
            ['qualification_id' => 56, 'qualification_name' => 'BFA Fine Arts'],
            ['qualification_id' => 57, 'qualification_name' => 'B.Sc. (Genl) Mathematical Science'],
            ['qualification_id' => 58, 'qualification_name' => 'B.Sc. (Hons) Anthropology'],
            ['qualification_id' => 59, 'qualification_name' => 'B.Sc. (Hons) Biomedical Science'],
            ['qualification_id' => 60, 'qualification_name' => 'B.Sc. (Hons) Chemistry'],
            ['qualification_id' => 61, 'qualification_name' => 'B.Sc. (Hons) Electronics'],
            ['qualification_id' => 62, 'qualification_name' => 'B.Sc. (Hons) Geology'],
            ['qualification_id' => 63, 'qualification_name' => 'B.Sc. (Hons) Mathematics'],
            ['qualification_id' => 64, 'qualification_name' => 'B.Sc. (Hons) Physics'],
            ['qualification_id' => 65, 'qualification_name' => 'B.Sc. (Hons) Statistics'],
            ['qualification_id' => 66, 'qualification_name' => 'B.Sc. (Hons.) Biological Sciences'],
            ['qualification_id' => 67, 'qualification_name' => 'B.Sc (PEHES)'],
            ['qualification_id' => 68, 'qualification_name' => 'B.Sc. Applied Life Sciences with Agro-Chemical & Pest Management'],
            ['qualification_id' => 69, 'qualification_name' => 'B.Sc. Applied Physical Science'],
            ['qualification_id' => 70, 'qualification_name' => 'B.Sc. Applied Physical Sciences (Industrial Chemistry)'],
            ['qualification_id' => 71, 'qualification_name' => 'B.Sc. Industrial Chemistry'],
            ['qualification_id' => 72, 'qualification_name' => 'B.Sc. Physical Sciences'],
            ['qualification_id' => 73, 'qualification_name' => 'B.Sc. Physical Science Computer Science'],
            ['qualification_id' => 74, 'qualification_name' => 'B.Sc. Physical Science with Computer'],
            ['qualification_id' => 75, 'qualification_name' => 'B.Sc. (Hons.) Instrumentation'],
            ['qualification_id' => 76, 'qualification_name' => 'B.Sc. (Hons) Bio-Chemistry'],
            ['qualification_id' => 77, 'qualification_name' => 'B.Sc. (Hons) Botany'],
            ['qualification_id' => 78, 'qualification_name' => 'B.Sc. (Hons) Computer Science'],
            ['qualification_id' => 79, 'qualification_name' => 'B.Sc. (Hons) Food Technology'],
            ['qualification_id' => 80, 'qualification_name' => 'B.Sc. (Hons) Home Science'],
            ['qualification_id' => 81, 'qualification_name' => 'B.Sc. (Hons) Microbiology'],
            ['qualification_id' => 82, 'qualification_name' => 'B.Sc. (Hons) Polymer Science'],
            ['qualification_id' => 83, 'qualification_name' => 'B.Sc. (Hons) Zoology'],
            ['qualification_id' => 84, 'qualification_name' => 'B.Sc. (MT) Radiography'],
            ['qualification_id' => 85, 'qualification_name' => 'B.Sc. Applied Life Sciences'],
            ['qualification_id' => 86, 'qualification_name' => 'B.Sc. Applied Science'],
            ['qualification_id' => 87, 'qualification_name' => 'B.Sc. Applied Physical Science (Analytical Chemistry)'],
            ['qualification_id' => 88, 'qualification_name' => 'B.Sc. Home Science (Pass)'],
            ['qualification_id' => 89, 'qualification_name' => 'B.Sc. Life Sciences'],
            ['qualification_id' => 90, 'qualification_name' => 'B.Sc. Physical Education & Sports Sciences'],
            ['qualification_id' => 91, 'qualification_name' => 'B.Sc. Physical Science with Chemistry'],
            ['qualification_id' => 92, 'qualification_name' => 'Bachelor of Business Studies'],
            ['qualification_id' => 93, 'qualification_name' => 'Bachelor of Financial & Investment Analysis'],
            ['qualification_id' => 94, 'qualification_name' => 'M.A. - M.Sc. (Home Science) Master in Home Science'],
            ['qualification_id' => 95, 'qualification_name' => 'M.Arch. Master of Architecture'],
            ['qualification_id' => 96, 'qualification_name' => 'M.A. Master of Arts'],
            ['qualification_id' => 97, 'qualification_name' => 'M.B.A. Master of Business Administration'],
            ['qualification_id' => 98, 'qualification_name' => 'M.Com. Master of Commerce'],
            ['qualification_id' => 99, 'qualification_name' => 'M.C.A. Master of Computer Applications'],
            ['qualification_id' => 100, 'qualification_name' => 'M.Des. - M.Design. Master of Design'],
            ['qualification_id' => 101, 'qualification_name' => 'M.Ed. Master of Education'],
            ['qualification_id' => 102, 'qualification_name' => 'M.E./M.Tech. Master of Engineering - Master of Technology'],
            ['qualification_id' => 103, 'qualification_name' => 'MFA - MVA Master of Fine Arts'],
            ['qualification_id' => 104, 'qualification_name' => 'M.F.Sc. - M.Sc. (Fisheries) Master of Fishery Science'],
            ['qualification_id' => 105, 'qualification_name' => 'L.L.M. Master of Laws'],
            ['qualification_id' => 106, 'qualification_name' => 'M.Lib. - M.Lib.Sc. Master of Library Science'],
            ['qualification_id' => 107, 'qualification_name' => 'M.M.C - M.M.M. Master of Mass Communications'],
            ['qualification_id' => 108, 'qualification_name' => 'M.Pharm Master of Pharmacy'],
            ['qualification_id' => 109, 'qualification_name' => 'M.Phil. Master of Philosophy'],
            ['qualification_id' => 110, 'qualification_name' => 'M.P.Ed. - M.P.E. Master of Physical Education'],
            ['qualification_id' => 111, 'qualification_name' => 'M.P.T. Master of Physiotherapy'],
            ['qualification_id' => 112, 'qualification_name' => 'M.Sc. Master of Science'],
            ['qualification_id' => 113, 'qualification_name' => 'M.Sc. (Agriculture) Master of Science in Agriculture'],
            ['qualification_id' => 114, 'qualification_name' => 'M.S.W. or M.A. (SW) Master of Social Work'],
            ['qualification_id' => 115, 'qualification_name' => 'M.V.Sc. Master of Veterinary Science'],
            ['qualification_id' => 116, 'qualification_name' => 'Ph.D. Doctor of Philosophy'],
            ['qualification_id' => 117, 'qualification_name' => 'Others'],
        ];

        DB::table('qualifications')->upsert(
            $qualifications,
            ['qualification_id'], // unique
            ['qualification_name'] // update if exists
        );

        // Reset sequence/auto increment for portability
        AutoIncrement::resetIndex('qualifications', 'qualification_id');
    }
}
