<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QualificationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $qualifications = [
            ['qualification_name' => 'Xth Class'],
            ['qualification_name' => 'XIIth Class'],
            ['qualification_name' => 'B.A. Bachelor of Arts'],
            ['qualification_name' => 'B.Arch. Bachelor of Architecture'],
            ['qualification_name' => 'B.Com. Bachelor of Commerce'],
            ['qualification_name' => 'BCA Bachelor of Computer Applications'],
            ['qualification_name' => 'BBA Bachelor of Business Administration'],
            ['qualification_name' => 'B.A.M.S. Bachelor of Ayurvedic Medicine & Surgery'],
            ['qualification_name' => 'B.Sc. (Computer Science) Bachelor of Computer Science'],
            ['qualification_name' => 'BDS Bachelor of Dental Surgery'],
            ['qualification_name' => 'B.Des. - B.D. Bachelor of Design'],
            ['qualification_name' => 'B.E./B.Tech. Bachelor of Engineering - Bachelor of Technology'],
            ['qualification_name' => 'BFA - BVA Bachelor of Fine Arts'],
            ['qualification_name' => 'B.F.Sc. - B.Sc. (Fisheries) Bachelor of Fisheries Science'],
            ['qualification_name' => 'B.A. - B.Sc. (Home Science) Bachelor of Home Science'],
            ['qualification_name' => 'B.H.M.S. Bachelor of Homeopathic Medicine and Surgery'],
            ['qualification_name' => 'L.L.B. Bachelor of Laws'],
            ['qualification_name' => 'B.Lib. - B.Lib.Sc. Bachelor of Library Science'],
            ['qualification_name' => 'B.M.C. - B.M.M. Bachelor of Mass Communications'],
            ['qualification_name' => 'B.Sc. (Nursing) Bachelor of Nursing'],
            ['qualification_name' => 'B.Pharm. Bachelor of Pharmacy'],
            ['qualification_name' => 'B.P.Ed. Bachelor of Physical Education'],
            ['qualification_name' => 'B.P.T. Bachelor of Physiotherapy'],
            ['qualification_name' => 'B.Sc. Bachelor of Science'],
            ['qualification_name' => 'BSW or B.A. (SW) Bachelor of Social Work'],
            ['qualification_name' => 'B.V.Sc. Bachelor of Veterinary Science & Animal Husbandry'],
            ['qualification_name' => 'B.Sc. (Agriculture) Bachelor of Agriculture'],
            ['qualification_name' => 'B.A. (Hons) Applied Psychology'],
            ['qualification_name' => 'B.A. (Hons) Bengali'],
            ['qualification_name' => 'B.A. (Hons) Economics'],
            ['qualification_name' => 'B.A. (Hons) French'],
            ['qualification_name' => 'B.A. (Hons) German'],
            ['qualification_name' => 'B.A. (Hons) History'],
            ['qualification_name' => 'B.A. (Hons) Italian'],
            ['qualification_name' => 'B.A. (Hons) Music'],
            ['qualification_name' => 'B.A. (Hons) Philosophy'],
            ['qualification_name' => 'B.A. (Hons) Psychology'],
            ['qualification_name' => 'B.A. (Hons) Sanskrit'],
            ['qualification_name' => 'B.A. (Hons) Sociology'],
            ['qualification_name' => 'B.A. (Hons) Urdu'],
            ['qualification_name' => 'B.A. Functional Hindi'],
            ['qualification_name' => 'B.A. (Hons) Arabic'],
            ['qualification_name' => 'B.A. (Hons) Business Economics (BBE)'],
            ['qualification_name' => 'B.A. (Hons) English'],
            ['qualification_name' => 'B.A. (Hons) Geography'],
            ['qualification_name' => 'B.A. (Hons) Hindi'],
            ['qualification_name' => 'B.A. (Hons) Patrakarita Evam Jansanchar'],
            ['qualification_name' => 'B.A. (Hons) Journalism'],
            ['qualification_name' => 'B.A. (Hons) Persian'],
            ['qualification_name' => 'B.A. (Hons) Political Science'],
            ['qualification_name' => 'B.A. (Hons) Punjabi'],
            ['qualification_name' => 'B.A. (Hons) Social Work'],
            ['qualification_name' => 'B.A. (Hons) Spanish'],
            ['qualification_name' => 'B.A. (Hons.) Hindi Journalism and Mass Communication'],
            ['qualification_name' => 'B.A. Vocational Studies'],
            ['qualification_name' => 'BFA Fine Arts'],
            ['qualification_name' => 'B.Sc. (Genl) Mathematical Science'],
            ['qualification_name' => 'B.Sc. (Hons) Anthropology'],
            ['qualification_name' => 'B.Sc. (Hons) Biomedical Science'],
            ['qualification_name' => 'B.Sc. (Hons) Chemistry'],
            ['qualification_name' => 'B.Sc. (Hons) Electronics'],
            ['qualification_name' => 'B.Sc. (Hons) Geology'],
            ['qualification_name' => 'B.Sc. (Hons) Mathematics'],
            ['qualification_name' => 'B.Sc. (Hons) Physics'],
            ['qualification_name' => 'B.Sc. (Hons) Statistics'],
            ['qualification_name' => 'B.Sc. (Hons.) Biological Sciences'],
            ['qualification_name' => 'B.Sc (PEHES)'],
            ['qualification_name' => 'B.Sc. Applied Life Sciences with Agro-Chemical & Pest Management'],
            ['qualification_name' => 'B.Sc. Applied Physical Science'],
            ['qualification_name' => 'B.Sc. Applied Physical Sciences (Industrial Chemistry)'],
            ['qualification_name' => 'B.Sc. Industrial Chemistry'],
            ['qualification_name' => 'B.Sc. Physical Sciences'],
            ['qualification_name' => 'B.Sc. Physical Science Computer Science'],
            ['qualification_name' => 'B.Sc. Physical Science with Computer'],
            ['qualification_name' => 'B.Sc. (Hons.) Instrumentation'],
            ['qualification_name' => 'B.Sc. (Hons) Bio-Chemistry'],
            ['qualification_name' => 'B.Sc. (Hons) Botany'],
            ['qualification_name' => 'B.Sc. (Hons) Computer Science'],
            ['qualification_name' => 'B.Sc. (Hons) Food Technology'],
            ['qualification_name' => 'B.Sc. (Hons) Home Science'],
            ['qualification_name' => 'B.Sc. (Hons) Microbiology'],
            ['qualification_name' => 'B.Sc. (Hons) Polymer Science'],
            ['qualification_name' => 'B.Sc. (Hons) Zoology'],
            ['qualification_name' => 'B.Sc. (MT) Radiography'],
            ['qualification_name' => 'B.Sc. Applied Life Sciences'],
            ['qualification_name' => 'B.Sc. Applied Science'],
            ['qualification_name' => 'B.Sc. Applied Physical Science (Analytical Chemistry)'],
            ['qualification_name' => 'B.Sc. Home Science (Pass)'],
            ['qualification_name' => 'B.Sc. Life Sciences'],
            ['qualification_name' => 'B.Sc. Physical Education & Sports Sciences'],
            ['qualification_name' => 'B.Sc. Physical Science with Chemistry'],
            ['qualification_name' => 'Bachelor of Business Studies'],
            ['qualification_name' => 'Bachelor of Financial & Investment Analysis'],
            ['qualification_name' => 'M.A. - M.Sc. (Home Science) Master in Home Science'],
            ['qualification_name' => 'M.Arch. Master of Architecture'],
            ['qualification_name' => 'M.A. Master of Arts'],
            ['qualification_name' => 'M.B.A. Master of Business Administration'],
            ['qualification_name' => 'M.Com. Master of Commerce'],
            ['qualification_name' => 'M.C.A. Master of Computer Applications'],
            ['qualification_name' => 'M.Des. - M.Design. Master of Design'],
            ['qualification_name' => 'M.Ed. Master of Education'],
            ['qualification_name' => 'M.E./M.Tech. Master of Engineering - Master of Technology'],
            ['qualification_name' => 'MFA - MVA Master of Fine Arts'],
            ['qualification_name' => 'M.F.Sc. - M.Sc. (Fisheries) Master of Fishery Science'],
            ['qualification_name' => 'L.L.M. Master of Laws'],
            ['qualification_name' => 'M.Lib. - M.Lib.Sc. Master of Library Science'],
            ['qualification_name' => 'M.M.C - M.M.M. Master of Mass Communications'],
            ['qualification_name' => 'M.Pharm Master of Pharmacy'],
            ['qualification_name' => 'M.Phil. Master of Philosophy'],
            ['qualification_name' => 'M.P.Ed. - M.P.E. Master of Physical Education'],
            ['qualification_name' => 'M.P.T. Master of Physiotherapy'],
            ['qualification_name' => 'M.Sc. Master of Science'],
            ['qualification_name' => 'M.Sc. (Agriculture) Master of Science in Agriculture'],
            ['qualification_name' => 'M.S.W. or M.A. (SW) Master of Social Work'],
            ['qualification_name' => 'M.V.Sc. Master of Veterinary Science'],
            ['qualification_name' => 'Others'],
        ];

        DB::table('qualifications')->upsert(
            $qualifications,
            ['qualification_name'], // unique
            [] // nothing to update, only insert if not exists
        );
    }
}
